### ISSUE TITLE
Consider migrating some of the content in "Getting Started" to a new category like "Futher Configuration"

### ISSUE THREAD

**Issue by ghost** [libretro/docs#29]
This mainly applies to the documents, I'm writing in my repo.

But is a reminder for me (and anyone else) whilst editing.

**Comment by andres-asm** [comment]
I don't understand why, it anything it's too basic

**Comment by ghost** [comment]
@fr500 
Hey sorry, this was mainly a note for my documentation that I'm writing on my fork (github issues didn't seem to work when I forked it for some reason). Although it could apply for other writings here too.

The reason why I wanted to do this, is that Getting Started should only focus on that. Honestly the changes will probably be minor.

As for it being too basic, I'm actually trying to add more sections to Getting Started. I've left stuff in there that would be better for another section

**Comment by CuttleFishJones8652** [comment]
Issues don't work on your fork? Explain.

**Comment by ghost** [comment]
@Hedonium 
Issues tab is not present. https://github.com/zayuim/docs

**Comment by CuttleFishJones8652** [comment]
https://help.github.com/articles/disabling-issues/

**Comment by ghost** [comment]
@Hedonium 

I've fixed it. But I still think it should stay here so other may understand what i'm doing, and perhaps others who like the idea can follow.

**Comment by andres-asm** [comment]
The split is horrible in my opinion....
Getting started was supposed to contain concise but complete guides for every platform.

Having to go to a different topic for the basics flat out sucks.

**Comment by thatman84** [comment]
In the absence of "full" getting started guides for all platforms its possible splitting the process up may help get more info committed.

Contributers may feel confident on submitting info on more bite size chunks than full guides.

I would not suggest removing the windows guide and when i get back to working on docs i will be putting it back at the top of the list rather than keyboard controls.

**Comment by ghost** [comment]
@fr500 

IMO getting started should only target RetroArch. Platform specific instructions are off in downloading/installing or differences/problems should be mentioned in the relevant Getting Started page.

Concise is good, but my goal was to introduce and help people with learning RetroArch. If someone is confused about setting up a controller then dedicating an article about it is beneficial. A guide written as a progression will help more then it will hurt.

This is where my idea for separating non-essential configs came from. If platform confusion is a problem, I'll put my GIMP/Inkscape skills to the test and make some flowcharts.

**Comment by fr500** [comment]
Well I'm entitled to have my opinion.
I wrote the getting started and I found it more usable before. Now when I refer users to it they still don't get the whole idea.

I was actually gonna add stuff to it but now I don't really know what to do...

**Comment by ghost** [comment]
@fr500 

> Well I'm entitled to have my opinion.

If you're open to having it changed, I'm taking some inspiration off [OpenStreetMap's beginners guide](https://wiki.openstreetmap.org/wiki/Beginners%27_guide), By splitting actions into byte sized parts, I think it makes it more accessible. But I'm also not saying mine is currently perfect. I even make the argument that this [other official guide](https://www.libretro.com/index.php/getting-started-with-retroarch/) (quite old) does a better job then the current beginners guide.

> they still don't get the whole idea.

You're not talking about my new documents are you? Because the table of contents has not yet been updated to include any of them, only the one on my [repo](https://github.com/zayuim/docs/) has.

> now I don't really know what to do...

Improve. I added some perfectly good documents, none are official right now. So prove that clumping them into a per platform basis is better then sorting them logically (installing retroarch, downloading cores, importing roms etc.).

**Comment by CuttleFishJones8652** [comment]
Please close this issue and move the discussion to over here.

https://github.com/libretro/docs/issues/4

I want the discussion about mkdocs.yml to be all in one place. 🙂
